### ISSUE TITLE
Interval setting for running OCC calls?

### ISSUE THREAD

**Issue by pjft** [Blaok/nextcloud-inotifyscan#19]
Apologies for opening this issue. I thought that the interval setting would set the seconds between polling for changes, but it seems to be more nuanced than that, so let me explain what I'm trying to accomplish in case there's an easy way to go about it.

The script works great as is, which is awesome and fits the purpose. The challenge I face is that when copying/creating large files to the external storage the CPU is basically constantly being hogged by running consecutive occ processes (even if they're shallow). For instance, I record 15h of video footage per week on that drive, on hourly chunks, which means that for the duration of those 15h we'll always be running OCC and logging to syslog that we found file modifications and that we are scanning it (the syslog file even got to 256MB at one point).

I tried to set the interval to 60s hoping that it would reduce the OCC runs to once a minute but clearly that didn't work as intended. Any thoughts on how to accomplish this scenario, or is it something that I'll just have to live with (and potentially manually removing the logging lines from the script on my machine)?

Thanks.

**Comment by Blaok** [comment]
Actually I agree the default logging level is somewhat too verbose if changes are frequent. You can make the script less verbose by passing `--quiet` to it. If that solves your problem, it's probably the best solution to go.

The interval setting does not control how frequent occ runs; instead, it controls how long to wait before trying to find new changes **if there is no change**. That is, it controls the worst-case latency between a change is made on disk and the server is informed. So if changes are created very frequently, they will be processed (by running occ scan) very frequently. This is by design, to scan the changes as soon as possible.

One thing that might worth researching is the list of event that `inotifywait` monitors. Currently `create,modify,move,delete` trigger scan. I think I did quite some experiments and decided to use these, but they may not be perfect for all use cases. In particular, I think `modify` is triggered every time a file is written, which may be triggered many times if it's a large file. Using `close_write` instead of `modify` might reduce the frequency of scans; not sure if it'll bring problems, though.

**Comment by pjft** [comment]
Thank you so much - these clarify the original intent and also provide some avenues for me to explore. Between --quiet and exploring `close_write` I imagine that those will sort out the scenario I'm trying to avoid. 

Thank you!

**Comment by pjft** [comment]
Just to confirm that from what I read and from brief testing, close_write works as intended - at the expense of not updating the file size in real-time as it's being written, which works well for my case at least.

Thank you.

**Comment by Blaok** [comment]
Cool! Glad that it worked.
