### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by schniepp** [Blaok/nextcloud-inotifyscan#2]
So inotifywait watches a tree in my data files folder, correct? 
I would like it to watch changed files  in an external share. However, this share does not show up in my files folder. It will only show up in the web interface. (The point of a mounted share is that it is sitting _elsewhere_.) So will this still work? Or would I have to modify your script such that it watches the actual places of the data? 

I also noticed that you are assuming that the data folder is sitting in the nextcloud folder. However, it can be any location. I amended the python script a bit so that it automatically pulls the 'datadirectory' variable from 'config/config.php'. However, not sure if it's worth creating a pull request. Also, I don't really know how github works... let me know.

**Comment by adrfantini** [comment]
> I amended the python script a bit so that it automatically pulls the 'datadirectory' variable from 'config/config.php'. However, not sure if it's worth creating a pull request. Also, I don't really know how github works... let me know.

I have been using icewind1991/files_inotify so far and it has some issues (icewind1991/files_inotify/issues/9), so I would like to switch to this tool. I would greatly appreciate if you could fork or do a pull request, since I would think that for most people external storage is NOT inside the `data` folder. I have not tested this tool yet tho, maybe you can workaround it with symlinks?

**Comment by Blaok** [comment]
Doesn't seem to be a complicated issue. I think I can take a look in a few days. I actually use `mount --bind` inside the data folder but it's not too hard to make it support arbitrary data folder.

**Comment by adrfantini** [comment]
> I actually use `mount --bind` inside the data folder
One huge disadvantage of this is that you need to do a bind for each user, if I am not mistaken.

**Comment by Blaok** [comment]
> > I actually use `mount --bind` inside the data folder

> One huge disadvantage of this is that you need to do a bind for each user, if I am not mistaken.

Not necessarily. I use it in the same way as using a symlink except I have to `mount` (as root, every boot). Good thing is it bypasses the permission check when you track the linked target (which is why I use `mount`; some of the parent folders of the target are not readable by the web server and I don't want to change that).

**Comment by Blaok** [comment]
@adrfantini Could you take a look and see if [this branch]( https://github.com/Blaok/nextcloud-inotifyscan/tree/data-dir) works? You can set `Environment=DATA_DIR=/path/to/data`.

**Comment by Blaok** [comment]
@schniepp I like your idea of reading `config/config.php` for `datadirectory`. Please feel free to make a PR if you have time! Much appreciated.

**Comment by adrfantini** [comment]
> @adrfantini Could you take a look and see if [this branch](https://github.com/Blaok/nextcloud-inotifyscan/tree/data-dir) works? You can set `Environment=DATA_DIR=/path/to/data`.

I'll do this for the next server maintenance. What if I want to monitor multiple External Storage folders? `files_inotify` allows for this by starting different services, one per External Storage target.

**Comment by apippin** [comment]
I needed the same feature you were looking for, and I liked the approach this project took in general to deal with these updates. I forked the project to apippin/nextcloud-inotifyscan and added the ability for it to launch multiple threads in parallel to watch multiple user (USER_NAME can now be a space separated list of users to have their directories watched) and all external storage folders at the same time. Instead of starting a different service for each path to watch, these changes enable inotifyscan to be a self contained service that can watch multiple paths in parallel. It works for my needs, but may be too big of a change from the original script for a pull request. I'll let the devs ponder on that one...

**Comment by Blaok** [comment]
@apippin Cool! I'll have to take a closer look later, though. Thanks.

**Comment by DaWy** [comment]
Hi. I'm trying to use this along with a remote network share folder, but the daemon isn't notifying anything. I tried to run inotifywatch in my own, and it does not report any change inside a remote network share (i tried Samba and NFS).

How are you making this working with this external  storage configuration? Am I missing something? Been struggling with this about 2 days without getting this solved. 

Tried also https://github.com/icewind1991/files_inotify but isn't notifying anything too... It would be nice to know what are your approatching and try to replicate it on my own.

Thanks!

**Comment by apippin** [comment]
Great question. The external mounts this works for are mounts on the server filesystem that are outside of the nextcloud data directory, but local to the nextcloud server. That is what is meant by "external" mounts as these are added as external mounts under the nextcloud account. This works for me since the mounts are local. I don't believe the inotify approach can work with SMB or NFS. A good link that discusses this in detail can be found here: https://unix.stackexchange.com/questions/81663/why-are-inotify-events-different-on-an-nfs-mount

**Comment by Blaok** [comment]
@DaWy Good point. I actually meant "external change in local storage" rather than "external storage". I updated the wording in my latest commit.

**Comment by Blaok** [comment]
The data directory is now configured based on `config.php`.

**Comment by Blaok** [comment]
Multiple users and even multiple Nextcloud installations can be watched simultaneously now (#6). I didn't use multithreading because parallel scanning can be very slow on HDDs.

I think this addresses all the concerns so far and therefore I'm closing this issue now.

**Comment by Blaok** [comment]
Sorry I misunderstood your original issue until just now --- you need the **external storages** to be watched and scanned, which won't be applicable unless the "External storage support" app is enabled. @apippin's fork seems to solve the problem. I'll try to port it in my latest code.

**Comment by Blaok** [comment]
#7 should solve this. @apippin thanks but sorry your code is too hard to merge and I decided to reinvent the wheel.
